name: Bug Report
description: Is something wrong? Let us know.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Ex. v1.2.3 / main / Commit 1a2b3c"

  - type: input
    id: os
    attributes:
      label: Environment
      description: "OS / Emulator / Multiplexer / etc."
