name: Feature Request
description: Suggest a new feature.
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
